# Generated by Django 5.0.1 on 2024-07-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_completed_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Thanh toán khi giao hàng')], default='Cash on Delivery', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Đang chờ xử lý'), ('Processing', 'Đang xử lý'), ('Shipped', 'Đã vận chuyển'), ('Delivered', 'Đã giao hàng'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
